In [101]:
# Import statements
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# CONSTANTS
INPUT_DIRECTORY = '/Users/E1T5/Desktop/survivor/survivor-csv'
OUTPUT_DIRECTORY = f"{INPUT_DIRECTORY}/output"

%matplotlib inline

# Airline dataset
# https://jblevins.org/notes/airline-data

In [103]:
# Load all files
challenge_description_df = pd.read_csv(f'{INPUT_DIRECTORY}/challenge_description.csv')
challenges_df = pd.read_csv(f'{INPUT_DIRECTORY}/challenges.csv')
challenge_results_df = pd.read_csv(f'{INPUT_DIRECTORY}/challenge_results.csv')
castaways_df = pd.read_csv(f'{INPUT_DIRECTORY}/castaways.csv')
castaway_details_df = pd.read_csv(f'{INPUT_DIRECTORY}/castaway_details.csv')
confessionals_df = pd.read_csv(f'{INPUT_DIRECTORY}/confessionals.csv')
hidden_idols_df = pd.read_csv(f'{INPUT_DIRECTORY}/hidden_idols.csv')
jury_votes_df = pd.read_csv(f'{INPUT_DIRECTORY}/jury_votes.csv')
season_palettes_df = pd.read_csv(f'{INPUT_DIRECTORY}/season_palettes.csv')
season_summary_df = pd.read_csv(f'{INPUT_DIRECTORY}/season_summary.csv')
tribe_colours_df = pd.read_csv(f'{INPUT_DIRECTORY}/tribe_colours.csv')
tribe_mapping_df = pd.read_csv(f'{INPUT_DIRECTORY}/tribe_mapping.csv')
viewers_df = pd.read_csv(f'{INPUT_DIRECTORY}/viewers.csv')
vote_history_df = pd.read_csv(f'{INPUT_DIRECTORY}/vote_history.csv')

In [104]:
# Combine multiple challenge datasets into a single df using 'challenge_id' column
challenge_merged_df = pd.merge(challenge_results_df, challenge_description_df, how="outer", on=['challenge_id'])

# remove unecessary columns and rows where the challenges did not exist on any challenge result
UNNECESSARY_FIELDS = ['version', 'Unnamed: 0_x', 'Unnamed: 0_y', 'challenge_name_y']
challenge_merged_clean_df = challenge_merged_df.drop(UNNECESSARY_FIELDS, axis=1).dropna()

# remove latest season 42
challenge_merged_clean_df = challenge_merged_clean_df[challenge_merged_clean_df['season'] != 42]

# sort by season
SORTING_FIELDS = ['season', 'episode', 'day', 'challenge_id']
challenge_merged_clean_df.sort_values(by=SORTING_FIELDS, inplace=True)

# extract out the challenges to a csv
challenges_filepath = f'{OUTPUT_DIRECTORY}/challenges-merged.csv'
challenge_merged_clean_df.to_csv(challenges_filepath, index = False)

# TODO NEED TO GET ANOTHER DF from the Rstudio for the winners. the winners are stored in a list on a field which makes it tricky to extract

In [142]:
# combine winners with contestant information
# RUNNER_UP_FIELDS = 'first_runner_up, second_runner_up'
DROP_CASTAWAY_FIELDS = ['version', 'Unnamed: 0_x', 'Unnamed: 0_y', 'personality_type_x', 'full_name_x']
castaways_all_df = pd.merge(castaways_df, castaway_details_df, on='castaway_id').drop(DROP_CASTAWAY_FIELDS, axis=1)
castaways_all_df = castaways_all_df.rename(columns={'personality_type_y': 'personality_type', 'full_name_y':'full_name'})

# define what kind of standing the person got
STANDING = 'standing'
castaways_all_df[STANDING] = 'Loser'
castaways_all_df.loc[castaways_all_df['jury_status'].str.contains('jury') > 0, STANDING] = 'Juror'

# TODO - find if it gives both runner ups. I dont think it does so we have to mash the data
castaways_all_df.loc[castaways_all_df['result'].str.contains('runner') > 0, STANDING] = 'Runner Up'
castaways_all_df.loc[castaways_all_df['result'] == 'Sole Survivor', STANDING] = 'Sole Survivor'

# split the Myersbrigs into 4 columns
castaways_all_df['myers_ie'] = castaways_all_df['personality_type'].str[0]
castaways_all_df['myers_sn'] = castaways_all_df['personality_type'].str[1]
castaways_all_df['myers_tf'] = castaways_all_df['personality_type'].str[2]
castaways_all_df['myers_pj'] = castaways_all_df['personality_type'].str[3]


# found = df[df['Column'].str.contains('Text_to_search')]

# extract out the castaways to a csv
castaway_filepath = f'{OUTPUT_DIRECTORY}/castaways_all.csv'
castaways_all_df.to_csv(castaway_filepath, index = False)

castaways_all_df.head()

,version_season,season_name,season,castaway_id,castaway,age,city,state,episode,day,...,race,ethnicity,poc,occupation,personality_type,standing,myers_ie,myers_sn,myers_tf,myers_pj
0,US01,Survivor: Borneo,1,US0016,Richard,39,Newport,Rhode Island,14.0,39.0,...,NaN,NaN,White,Corporate Trainer,ENTP,Sole Survivor,E,N,T,P
1,US08,Survivor: All-Stars,8,US0016,Richard,42,Middletown,Rhode Island,5.0,15.0,...,NaN,NaN,White,Corporate Trainer,ENTP,Loser,E,N,T,P
2,US01,Survivor: Borneo,1,US0015,Kelly,22,Kernville,California,14.0,39.0,...,NaN,NaN,White,River Guide,ISFP,Loser,I,S,F,P
3,US31,Survivor: Cambodia,31,US0015,Kelly,37,Greensboro,North Carolina,9.0,24.0,...,NaN,NaN,White,River Guide,ISFP,Juror,I,S,F,P
4,US01,Survivor: Borneo,1,US0014,Rudy,72,Virginia Beach,Virginia,13.0,38.0,...,NaN,NaN,White,Retired Navy SEAL,ISTJ,Juror,I,S,T,J

In [ ]:
# High level stats of a df
titanic_df.describe()

In [ ]:
# Drop does not modify the df, but creates a new dataframe
titanic_df.drop(['Ticket', 'Cabin'], axis=1).head()

In [ ]:
# Proves that the df was not permantently changed
titanic_df.head()

In [ ]:
# Find which fields are null and count them up
titanic_df.isnull().sum()

In [ ]:
# Plot 
pd.value_counts(titanic_df['Survived']).plot.bar()

In [ ]:
# Group rows according to a certain column and then find a statistic on it (in this case the mean)
titanic_df.groupby(['Sex']).mean()

In [ ]:
# Group rows according to multiple columns and then find a statistic on it (in this case the mean)
titanic_df.groupby(['Sex', 'Pclass']).mean()

In [ ]:
# Filter the df by certain criteria (Age<18) and then group rows according to multiple columns 
titanic_df[titanic_df['Age']<18].groupby(['Sex', 'Pclass']).mean()

In [ ]:
# Find the index of a df
titanic_df.index

In [ ]:
#